### ISSUE TITLE
Cannot delete clipboard history

### ISSUE THREAD

**Issue by Locbac** [adirh3/Clipboard.Fluent.Plugin#3]
Everytime I go into the clipboard search, I try shift+delete and delete to delete the history, however it never deletes anything? I also tried clicking it manually and no luck. I do not have the windows built in clipboard manager enabled, though I wouldn't think that would be a problem.

**Comment by Locbac** [comment]
### Old Solution (May work for you)
- Fixed by completely killing fluent search, clearing everything from %temp% directory (You can access this by WIN+R, then typing in %temp%). I then ran the fluent search app as admin.
# New solution
1. Use revo uninstaller to uninstall and delete all traces of the fluent search app.
2. Download the nightly edition.
3. Right click the installer (I chose the exe)
4. Click Properties
5. If it shows unblock at the bottom then click it, if not you should be ok to close out of this tab.
6. Run the installer with admin
7. Download the clipboard plugin and test it out!

**Comment by Locbac** [comment]
Ok, it looks like it only worked once, I am still having issues with this.

**Comment by adirh3** [comment]
@Locbac have you checked it on stable or nightly version?

**Comment by Locbac** [comment]
@adirh3 I checked on the stable version. I'll try the nightly aswell, see if that fixes it.

**Comment by Locbac** [comment]
The nightly version after completely wiping every trace of fluent search via revo uninstaller fixed it.
